# Generated by Django 4.2.7 on 2025-11-26 00:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('multiple_choice', 'Множественный выбор'), ('fill_blank', 'Заполнение пропусков'), ('translation', 'Перевод'), ('question', 'Вопрос')], max_length=20, verbose_name='Тип упражнения')),
                ('question', models.TextField(verbose_name='Вопрос/Задание')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('options', models.JSONField(blank=True, default=list, help_text='Для множественного выбора - список вариантов', verbose_name='Варианты ответов')),
                ('explanation', models.TextField(blank=True, verbose_name='Объяснение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('points', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Баллы')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('icon', models.CharField(default='📚', max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория уроков',
                'verbose_name_plural': 'Категории уроков',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(verbose_name='Ответ пользователя')),
                ('is_correct', models.BooleanField(verbose_name='Правильно')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Заработано баллов')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Попытка')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lessons.exercise', verbose_name='Упражнение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка выполнения упражнения',
                'verbose_name_plural': 'Попытки выполнения упражнений',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('theory', models.TextField(verbose_name='Теоретический материал')),
                ('examples', models.TextField(help_text='Примеры использования, разделенные новой строкой', verbose_name='Примеры')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.lessoncategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='lessons.lesson', verbose_name='Урок'),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('score', models.IntegerField(default=0, verbose_name='Баллы')),
                ('total_points', models.IntegerField(default=0, verbose_name='Всего баллов')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='lessons.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
